version: "3.7"
services:
  app:
    container_name: server 
    restart: always
    build: .
    volumes:
      - ./app:/app
    networks:
      domestics:
        ipv4_address: 10.5.0.5
    ports:
      - "3000:3000"
    command: >
      sh -c "npm run dev"
    # links:
    #   - mongo
  mongo:
    container_name: database 
    image: mongo 
    restart: always
    networks:
      domestics:
        ipv4_address: 10.5.0.6
    ports:
      - "27017:27017"

networks:
  domestics:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
