version: "3.3"

# run in swarm

secrets:
  mongodb_url: 
    external: true
  port:
    external: true

services:
  app:
    container_name: app
    image: app
    restart: always
    build: .
    volumes:
      - ./app:/app
    networks:
      domestics:
        # ipv4_address: 10.5.0.5
    ports:
      - "3000:3000"
    secrets:                    # secrets block only for 'web' service
     - mongodb_url
     - port
    command: >
      sh -c "node src/index.js"
    depends_on:
      - mongo
    # links:
    #   - mongo

  mongo:
    container_name: mongo
    image: mongo 
    restart: always
    networks:
      domestics:
        # ipv4_address: 10.5.0.6
    ports:
      - "27017:27017"

  app-tests:
    image: app 
    networks:
      domestics:
        # ipv4_address: 10.5.0.8
    command: dockerize
      -wait tcp://mongo:27017 -wait tcp://app:3000 -timeout 20s
      sh -c "npm run test"
    depends_on:
      - app
      - mongo

networks:
  domestics:
    driver: overlay
    # ipam:
    #   config:
    #     - subnet: 10.5.0.0/16
    #       gateway: 10.5.0.1

